version = 1
SPDX-PackageName = "device-scheduler"
SPDX-PackageSupplier = "Weston Schmidt <weston_schmidt@alumni.purdue.edu>"
SPDX-PackageDownloadLocation = "https://github.com/xmidt-org/device-scheduler"

[[annotations]]
path = ".golangci.yaml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".codecov.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".yamllint.yml"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.mod"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "go.sum"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".gitignore"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ".whitesource"
precedence = "aggregate"
SPDX-FileCopyrightText = "2023 Comcast Cable Communications Management, LLC"
SPDX-License-Identifier = "Apache-2.0"
