# SPDX-FileCopyrightText: 2022 Comcast Cable Communications Management, LLC
# SPDX-License-Identifier: Apache-2.0
---
name: 'PROJ: xmidt-team'

on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  project:
    uses: xmidt-org/shared-go/.github/workflows/proj.yml@766cd1914571123cc26ab6e0f1782c784dc4f11f # v4.4.28
    secrets: inherit
